### PR TITLE
Different Websites To Practice

### PR DESCRIPTION
**Pull request by reapedjuggler**
Added a table containing different websites to practice

### CODE REVIEW

**Review by hemant2132 — DISMISSED** [review]
Try something like [Site-name](link) instead of "Site-name link".

If we have to maintain a table then we should probably add a column for "Description". Another choice for a column would be "Tips" (for effective usage of that particular site).

Also, add more Sites/OJs...

**Review by reapedjuggler — COMMENTED** [review]
We should add the description , maybe after the hands on

**Comment by hemant2132** [comment]
Yeah. But then I will prefer to merge this only when the description column has entries.

**Review by reapedjuggler — COMMENTED** [review]
Added a general description for each site.

**Review by hemant2132 — COMMENTED** [review]
I have made some changes. Have a look.

**Review by reapedjuggler — COMMENTED** [review]
It looks good , only a small suggestion change the word (scene to culture) in Code chef 's description .

**Comment by hemant2132** [comment]
@reapedjuggler Oh ok, I will do that. Plus, I'll probably add more sites/info in the future (to be specific, before the hands-on-session).

**Review by reapedjuggler — COMMENTED** [review]
Definitely that wont do any harm anytime , maybe for now we can merge this so that they can have a look at some of the OJs , eh ? and moreover i will be also adding more info and FAQs on beginner and intermediate programming

**Pull request merged**
