### PR TITLE
my collection of books

### PR DESCRIPTION
**Pull request by hemant2132**
Please cross-check if any of these books violates the copy-right rules.

### CODE REVIEW

**Review by utkarsh261 — CHANGES_REQUESTED** [review]
4 of 11 files have copyright statements
* Programming challenges
* The Algorithm design manual
* laaksonen2
* Competitive Programming 3

Should we remove them as-a-file and put links(from wherever one can download) in the README instead?
We would then not be hosting them, and can still share.

**Comment by hemant2132** [comment]
So, should I add links for only these 4 books or all of them?

**Comment by utkarsh261** [comment]
Yes that would be my opinion too.

**Comment by hemant2132** [comment]
Actually, I think we should not provide links to download but the links to buy the books (just to be safe 😅 ).

**Review by utkarsh261 — APPROVED** [review]
Looks good!
In future, I'll add links (to readable PDFs) for other books (those which are open-source) too, whether it be from this repo or elsewhere.
Advantages: 
* the repo size will be smaller, means faster pull/push
* I'd prefer links rather than opening the file on github and then downloading, because github doesn't support display of huge files.

I'll merge this, thanks.

**Comment by hemant2132** [comment]
Yeah. Will make this in mind.

**Pull request merged**
