### PR TITLE
Added various resources

### PR DESCRIPTION
**Pull request by hemant2132**
Will update the Tools section after the hands-on session.

### CODE REVIEW

**Review by reapedjuggler — COMMENTED** [review]
also you can add tushar roy (codingmadesimple) yt channel and clist.by (a site which shows live contests going on) ..

**Comment by hemant2132** [comment]
I'll put clist, CF Visualiser, Stopstalk and others under Tools later.
For Tushar Roy's YT channel, I may add it later (after the hands-on). Personally, I have not watched much of his videos...
By the way the "For more..." link mentions his channel.

**Review by reapedjuggler — COMMENTED** [review]
ok it goes fine then :+1:

**Comment by sosooding** [comment]
We should also add codechef's training camp youtube link probably.

**Comment by hemant2132** [comment]
Hmm, yeah we can add them. 
I'll add the links of the IPC camp's playlists (both [2016](https://www.youtube.com/playlist?list=PLi0ZM-RCX5nsTc2Z6woHr5qoF6n3b-thO) and [2017](https://www.youtube.com/playlist?list=PLi0ZM-RCX5nvImim3_ilsdLOtDDkOWt-X)) as well as the related [blog](https://www.codechef.com/ipc/camp/2017) to the Miscellaneous folder, ok?

**Comment by sosooding** [comment]
We can actually make a Youtube folder as well, because there is a lot of content, scattered around Youtube.

**Comment by hemant2132** [comment]
Currently, I have made a subtopic for YouTube in the Community folder's README file. So should I create a subfolder for YouTube (in the Community folder) instead?

**Comment by utkarsh261** [comment]
I think the subtopic is fine.

**Comment by hemant2132** [comment]
Ok then, just want to mention here that I will make changes as and when required to the "develop" branch and will make PRs accordingly.

**Pull request merged**
